---
title: "Analyse des données "
description:
    Courte analyse et visualisation des données de vaccinations, PIB et espérance de vie.
date: "`r Sys.Date()`"
author:
  - first_name: "Cynthia"
    last_name: "Bello"
    url: https://github.com/CynthiaBH
    affiliation: Université de Montréal
    affiliation_url: https://www.umontreal.ca/etudes/#domaines-d-etudes
citation_url: https://CynthiaBH.github.io/FAS1002_projet-final
bibliography: references.bib
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Un peu d'interactivité pour le plaisir!

```{r map, layout = "l-page"}
library(leaflet)
leaflet() %>%
  addTiles() %>%
  addMarkers(lng=174.768, lat=-36.852, popup="Là où R est né") %>%
  addProviderTiles(providers$Stamen.Watercolor)
```


## Peut-être que ça vous inspirera!

```{r plotly}
library(plotly)
library(gapminder)
df <- gapminder

fig <- df %>%
  plot_ly(
    x = ~ gdpPercap,
    y = ~ lifeExp,
    size = ~ pop,
    color = ~ continent,
    frame = ~ year,
    text = ~ country,
    hoverinfo = "text",
    type = 'scatter',
    mode = 'markers',
    width = "100%",
    height = 600
  )

fig <- fig %>% layout(xaxis = list(type = "log"))

fig <- fig %>%
  animation_button(
    x = 0, xanchor = "left", y = -0.15, yanchor = "bottom"
  )

fig
```


